### Requisição para a raiz
GET http://localhost:3000

### Requisição passando parâmetros na URL
GET http://localhost:3000/eletronico/celular

### Requisição passando informação pelo corpo da requisição
POST http://localhost:3000
Content-Type: application/json

{
    "Nome" : "Jorjinho",
    "CPF" : "999.888.777-66"
}
